### ISSUE TITLE
Cannot find the network command

### ISSUE THREAD

**Issue by sherifm** [ruffsl/ros_docker_demos#1]
Hi,

I'm trying to use ROS with Docker and can't seem to find the [docker network](https://github.com/ruffsl/ros_docker_demos/tree/master/multicontainer#creating-a-network) commands, that you recommend using to have ROS nodes talk to each other over a virtual network. Is this approach deprecated? Or do I need to install some sort of docker networking plug-in?

Thank you for your support!

**Comment by sherifm** [comment]
So it turns out the docker [experimental features](https://github.com/docker/docker/tree/master/experimental) are required rather than the official docker release.

Again thanks for your great contributions!

**Comment by ruffsl** [comment]
Hello @sherifm ,

The syntax I wrote up on the Docker Hub [ros reop](https://hub.docker.com/_/ros/) may be out of date, as the docker ecosystems changes so fast, expectantly APIs still in beta. Here is a [blog article](http://toddsampson.com/post/131227320927/docker-experimental-networking-and-ros) found in the comments of the ros repo that speaks more recently on the topic. Once the official network CLI for docker is released, hopefully in the [1.9 milstone](https://github.com/docker/docker/milestones), I'll revisit the documentation and update everything with a PR. Let me know if you have any questions with trying it all out!
